services:
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DB}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data